### PR TITLE
LeetcodeCreate first leetcode

### PR DESCRIPTION
**Pull request by MOHAMEDAJEEM**

### CODE REVIEW

**Comment by momo46060** [comment]
.

**Comment by hey-nivesh** [comment]
That's great!

**Comment by Aditya90456** [comment]
great

**Comment by 4K45HGU114** [comment]
great

**Comment by Babanjadhav1255** [comment]
great

**Comment by VivekBhurke** [comment]
Nice

**Comment by HikmetRzayev** [comment]
Nice

**Comment by vital290** [comment]
no

**Comment by varunpatel15** [comment]
thank you

**Review by dhanu2221 — APPROVED** [review]

**Review by Arunkumarvp — APPROVED** [review]

**Comment by mahmosha** [comment]
mind blown

**Pull request closed without merging**
